# https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md#testing-plugins

language: generic

os:
  - linux
  - osx

before_script:
  - git clone --branch v0.5.0 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

script: asdf plugin-test brig https://github.com/Ibotta/asdf-brig.git 'brig version'
