name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: brig version
      - name: asdf_plugin_test_with_v_prefix
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: v1.4.0
          command: brig version
      - name: asdf_plugin_test_without_v_prefix
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 1.4.0
          command: brig version
